# Soliguide: Useful information for those who need it
#
# SPDX-FileCopyrightText: © 2024 Solinum
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Develop - build, test and deploy

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    uses: ./.github/workflows/_commitlint.yml

  build:
    name: Build all packages (once)
    uses: ./.github/workflows/_build.yml
    needs:
      - commitlint
    secrets: inherit

  # Dès que le build est OK, on déploie ET on teste en parallèle
  deploy_clever_cloud:
    name: Deploy to Clever Cloud (staging)
    uses: ./.github/workflows/_deploy-to-environment.yml
    with:
      environment: staging
    needs:
      - build
    secrets: inherit

  deploy_qovery:
    name: Deploy to Qovery (develop)
    uses: ./.github/workflows/_deploy-to-test-qovery.yml
    with:
      deploy_api: ${{ contains(needs.build.outputs.to_deploy, 'api') }}
      deploy_frontend: ${{ contains(needs.build.outputs.to_deploy, 'frontend') }}
      deploy_location-api: ${{ contains(needs.build.outputs.to_deploy, 'location-api') }}
      deploy_soligare: ${{ contains(needs.build.outputs.to_deploy, 'soligare') }}
      deploy_web-app: ${{ contains(needs.build.outputs.to_deploy, 'web-app') }}
      deploy_widget: ${{ contains(needs.build.outputs.to_deploy, 'widget') }}
      create: true
    needs:
      - build
    secrets: inherit

  # Les tests utilisent les images déjà buildées (pas de rebuild)
  test:
    name: Test all packages (using built images)
    uses: ./.github/workflows/_test-only.yml
    with:
      docker_tag: develop
      node_version: ${{ needs.build.outputs.node_version }}
      test_api: ${{ contains(needs.build.outputs.to_deploy, 'api') }}
      test_common: ${{ contains(needs.build.outputs.to_deploy, 'common') }}
      test_common-angular: ${{ contains(needs.build.outputs.to_deploy, 'common-angular') }}
      test_design-system: ${{ contains(needs.build.outputs.to_deploy, 'design-system') }}
      test_frontend: ${{ contains(needs.build.outputs.to_deploy, 'frontend') }}
      test_location-api: ${{ contains(needs.build.outputs.to_deploy, 'location-api') }}
      test_soligare: ${{ contains(needs.build.outputs.to_deploy, 'soligare') }}
      test_web-app: ${{ contains(needs.build.outputs.to_deploy, 'web-app') }}
      test_widget: ${{ contains(needs.build.outputs.to_deploy, 'widget') }}
    needs:
      - build
    secrets: inherit
