# Soliguide: Useful information for those who need it
#
# SPDX-FileCopyrightText: Â© 2024 Solinum
#
# SPDX-License-Identifier: AGPL-3.0-only
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Hotfix - build and test

on:
  push:
    branches:
      - hotfix

jobs:
  commitlint:
    uses: ./.github/workflows/_commitlint.yml

  # Build all packages for hotfix
  build:
    name: Build all packages
    uses: ./.github/workflows/_build.yml
    needs:
      - commitlint
    secrets: inherit

  # Test using pre-built images (blocking for hotfix)
  test:
    name: Test all packages
    uses: ./.github/workflows/_test-only.yml
    with:
      docker_tag: hotfix
      test_api: true
      test_common: true
      test_common-angular: true
      test_design-system: true
      test_frontend: true
      test_location-api: true
      test_soligare: true
      test_web-app: true
      test_widget: true
    needs:
      - build
    secrets: inherit
